services:
  db:
    image: postgres:16-alpine
    container_name: futpro-db
    environment:
      POSTGRES_USER: pf
      POSTGRES_PASSWORD: pf
      POSTGRES_DB: futpro
    ports:
      - "5432:5432"
    volumes:
      - pf_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pf -d futpro"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pf_pgdata:
